language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "hoijui-github"
    token: ${SONAR_TOKEN}

jdk:
# Only test one JDK to save energy
#  - oraclejdk8
#  - oraclejdk11
  - openjdk8
#  - openjdk11

script:
# NOTE JaCoCo is used to have code coverage, the agent has to be activated
# NOTE The SonarCube Community Edition (free plan) only allows branch "master".
  - mvnExtra=""; if [ $TRAVIS_BRANCH = "master" ]; then mvnExtra="sonar:sonar"; fi; mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package $mvnExtra

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
